version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3010:3000
      - 5010:5000
    stdin_open: true
    # command: "bash"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './frontend:/app'
      # - '/app/node_modules'
    depends_on:
      - backend
    restart: always
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8082:8000
    stdin_open: true
    tty: true
    # command: "bash"
    environment:
      - PORT=8000
    volumes:
      - './backend:/app'
      # - '/app/node_modules'
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
